<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Organic Apples',
                'slug' => Str::slug('Organic Apples'),
                'price' => 800.00,
                'quantity' => 50,
                'discount_amount' => 100.00,
                'actual_amount' => 700.00,
                'image' => 'products/organic-apples.jpg',
                'description' => 'Fresh, organic apples sourced from local farms.',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium organic product
                'is_selling' => 1,  // High demand
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Fresh Carrots',
                'slug' => Str::slug('Fresh Carrots'),
                'price' => 500.00,
                'quantity' => 60,
                'discount_amount' => 50.00,
                'actual_amount' => 450.00,
                'image' => 'products/fresh-carrots.jpg',
                'description' => 'Crisp and fresh carrots, perfect for salads.',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Best-seller due to quantity
                'is_popular' => 1,  // Trending vegetable
                'is_new' => 0,
            ],
            [
                'name' => 'Full Cream Milk',
                'slug' => Str::slug('Full Cream Milk'),
                'price' => 120.00,
                'quantity' => 100,
                'discount_amount' => 20.00,
                'actual_amount' => 100.00,
                'image' => 'products/full-cream-milk.jpg',
                'description' => 'Rich and creamy full-fat milk.',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales volume
                'is_popular' => 1,  // Widely used
                'is_new' => 0,
            ],
            [
                'name' => 'Brown Rice',
                'slug' => Str::slug('Brown Rice'),
                'price' => 300.00,
                'quantity' => 40,
                'discount_amount' => 30.00,
                'actual_amount' => 270.00,
                'image' => 'products/brown-rice.jpg',
                'description' => 'Healthy brown rice for daily meals.',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Healthy standout
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // Recently introduced
            ],
            [
                'name' => 'Canned Beans',
                'slug' => Str::slug('Canned Beans'),
                'price' => 200.00,
                'quantity' => 70,
                'discount_amount' => 25.00,
                'actual_amount' => 175.00,
                'image' => 'products/canned-beans.jpg',
                'description' => 'Ready-to-eat canned beans, rich in protein.',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular pantry item
                'is_new' => 0,
            ],

            // Category 2: Electronics (category_id: 2)
            [
                'name' => 'Smartphone X',
                'slug' => Str::slug('Smartphone X'),
                'price' => 135000.00,
                'quantity' => 20,
                'discount_amount' => 6750.00,
                'actual_amount' => 128250.00,
                'image' => 'products/smartphone-x.jpg',
                'description' => 'Latest model smartphone with advanced features.',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium tech
                'is_selling' => 1,  // High demand
                'is_popular' => 1,  // Trending
                'is_new' => 1,     // New release
            ],
            [
                'name' => 'Wireless Earbuds',
                'slug' => Str::slug('Wireless Earbuds'),
                'price' => 13500.00,
                'quantity' => 30,
                'discount_amount' => 1350.00,
                'actual_amount' => 12150.00,
                'image' => 'products/wireless-earbuds.jpg',
                'description' => 'High-quality wireless earbuds with noise cancellation.',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Standout accessory
                'is_selling' => 0,
                'is_popular' => 1,  // Popular gadget
                'is_new' => 0,
            ],
            [
                'name' => 'LED TV 43"',
                'slug' => Str::slug('LED TV 43'),
                'price' => 54000.00,
                'quantity' => 15,
                'discount_amount' => 5400.00,
                'actual_amount' => 48600.00,
                'image' => 'products/led-tv-43.jpg',
                'description' => '43-inch LED TV with smart features.',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium TV
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Laptop Pro',
                'slug' => Str::slug('Laptop Pro'),
                'price' => 189000.00,
                'quantity' => 10,
                'discount_amount' => 18900.00,
                'actual_amount' => 170100.00,
                'image' => 'products/laptop-pro.jpg',
                'description' => 'High-performance laptop for professionals.',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // High-end product
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // New model
            ],
            [
                'name' => 'Smart Watch',
                'slug' => Str::slug('Smart Watch'),
                'price' => 27000.00,
                'quantity' => 25,
                'discount_amount' => 2700.00,
                'actual_amount' => 24300.00,
                'image' => 'products/smart-watch.jpg',
                'description' => 'Fitness tracking smart watch with heart rate monitor.',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Popular fitness item
                'is_popular' => 1,  // Trending
                'is_new' => 0,
            ],

            // Category 3: Fashion (category_id: 3)
            [
                'name' => 'Leather Jacket',
                'slug' => Str::slug('Leather Jacket'),
                'price' => 20250.00,
                'quantity' => 30,
                'discount_amount' => 2700.00,
                'actual_amount' => 17550.00,
                'image' => 'products/leather-jacket.jpg',
                'description' => 'Stylish leather jacket for all seasons.',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium fashion
                'is_selling' => 0,
                'is_popular' => 1,  // Trendy
                'is_new' => 0,
            ],
            [
                'name' => 'Cotton T-Shirt',
                'slug' => Str::slug('Cotton T-Shirt'),
                'price' => 1350.00,
                'quantity' => 50,
                'discount_amount' => 150.00,
                'actual_amount' => 1200.00,
                'image' => 'products/cotton-t-shirt.jpg',
                'description' => 'Comfortable cotton t-shirt for casual wear.',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Popular basic
                'is_new' => 0,
            ],
            [
                'name' => 'Running Shoes',
                'slug' => Str::slug('Running Shoes'),
                'price' => 6750.00,
                'quantity' => 40,
                'discount_amount' => 675.00,
                'actual_amount' => 6075.00,
                'image' => 'products/running-shoes.jpg',
                'description' => 'Lightweight running shoes for all terrains.',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 1,     // New arrival
            ],
            [
                'name' => 'Silk Scarf',
                'slug' => Str::slug('Silk Scarf'),
                'price' => 4050.00,
                'quantity' => 35,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/silk-scarf.jpg',
                'description' => 'Elegant silk scarf for a touch of class.',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Elegant accessory
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Denim Jeans',
                'slug' => Str::slug('Denim Jeans'),
                'price' => 5400.00,
                'quantity' => 45,
                'discount_amount' => 540.00,
                'actual_amount' => 4860.00,
                'image' => 'products/denim-jeans.jpg',
                'description' => 'Durable denim jeans with a modern fit.',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Trendy
                'is_new' => 0,
            ],

            // Category 4: Home & Furniture (category_id: 4)
            [
                'name' => 'Wooden Coffee Table',
                'slug' => Str::slug('Wooden Coffee Table'),
                'price' => 27000.00,
                'quantity' => 15,
                'discount_amount' => 4050.00,
                'actual_amount' => 22950.00,
                'image' => 'products/wooden-coffee-table.jpg',
                'description' => 'Elegant wooden coffee table for your living room.',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium furniture
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // New design
            ],
            [
                'name' => 'Cotton Bedsheet Set',
                'slug' => Str::slug('Cotton Bedsheet Set'),
                'price' => 4050.00,
                'quantity' => 25,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/cotton-bedsheet-set.jpg',
                'description' => 'Soft cotton bedsheet set for a cozy sleep.',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Popular bedding
                'is_popular' => 1,  // Widely liked
                'is_new' => 0,
            ],
            [
                'name' => 'Table Lamp',
                'slug' => Str::slug('Table Lamp'),
                'price' => 6750.00,
                'quantity' => 20,
                'discount_amount' => 675.00,
                'actual_amount' => 6075.00,
                'image' => 'products/table-lamp.jpg',
                'description' => 'Modern table lamp with adjustable brightness.',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Unique design
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Bookshelf',
                'slug' => Str::slug('Bookshelf'),
                'price' => 13500.00,
                'quantity' => 10,
                'discount_amount' => 1350.00,
                'actual_amount' => 12150.00,
                'image' => 'products/bookshelf.jpg',
                'description' => 'Sturdy bookshelf for organizing your collection.',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular storage
                'is_new' => 1,     // New arrival
            ],
            [
                'name' => 'Decorative Cushions',
                'slug' => Str::slug('Decorative Cushions'),
                'price' => 2700.00,
                'quantity' => 30,
                'discount_amount' => 270.00,
                'actual_amount' => 2430.00,
                'image' => 'products/decorative-cushions.jpg',
                'description' => 'Colorful cushions to enhance your decor.',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 0,
                'is_new' => 0,
            ],

            // Category 5: Beauty & Personal Care (category_id: 5)
            [
                'name' => 'Moisturizing Cream',
                'slug' => Str::slug('Moisturizing Cream'),
                'price' => 3375.00,
                'quantity' => 100,
                'discount_amount' => 675.00,
                'actual_amount' => 2700.00,
                'image' => 'products/moisturizing-cream.jpg',
                'description' => 'Hydrating cream for all skin types.',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Top skincare
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Lipstick Matte',
                'slug' => Str::slug('Lipstick Matte'),
                'price' => 1350.00,
                'quantity' => 80,
                'discount_amount' => 135.00,
                'actual_amount' => 1215.00,
                'image' => 'products/lipstick-matte.jpg',
                'description' => 'Long-lasting matte lipstick in vibrant shades.',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Trending
                'is_new' => 0,
            ],
            [
                'name' => 'Shampoo Herbal',
                'slug' => Str::slug('Shampoo Herbal'),
                'price' => 2025.00,
                'quantity' => 60,
                'discount_amount' => 202.50,
                'actual_amount' => 1822.50,
                'image' => 'products/shampoo-herbal.jpg',
                'description' => 'Gentle herbal shampoo for healthy hair.',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular choice
                'is_new' => 1,     // New formula
            ],
            [
                'name' => 'Face Wash',
                'slug' => Str::slug('Face Wash'),
                'price' => 1620.00,
                'quantity' => 70,
                'discount_amount' => 162.00,
                'actual_amount' => 1458.00,
                'image' => 'products/face-wash.jpg',
                'description' => 'Refreshing face wash for deep cleansing.',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High demand
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Perfume Floral',
                'slug' => Str::slug('Perfume Floral'),
                'price' => 5400.00,
                'quantity' => 40,
                'discount_amount' => 540.00,
                'actual_amount' => 4860.00,
                'image' => 'products/perfume-floral.jpg',
                'description' => 'Long-lasting floral perfume.',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium scent
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // New fragrance
            ],

            // Category 6: Sports & Fitness (category_id: 6)
            [
                'name' => 'Yoga Mat',
                'slug' => Str::slug('Yoga Mat'),
                'price' => 5400.00,
                'quantity' => 40,
                'discount_amount' => 1350.00,
                'actual_amount' => 4050.00,
                'image' => 'products/yoga-mat.jpg',
                'description' => 'Non-slip yoga mat for fitness enthusiasts.',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Top fitness item
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Dumbbell Set',
                'slug' => Str::slug('Dumbbell Set'),
                'price' => 6750.00,
                'quantity' => 25,
                'discount_amount' => 675.00,
                'actual_amount' => 6075.00,
                'image' => 'products/dumbbell-set.jpg',
                'description' => 'Adjustable dumbbell set for home workouts.',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Trending
                'is_new' => 1,     // New stock
            ],
            [
                'name' => 'Sports Bottle',
                'slug' => Str::slug('Sports Bottle'),
                'price' => 1350.00,
                'quantity' => 50,
                'discount_amount' => 135.00,
                'actual_amount' => 1215.00,
                'image' => 'products/sports-bottle.jpg',
                'description' => 'Leak-proof sports bottle for hydration.',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Popular accessory
                'is_new' => 0,
            ],
            [
                'name' => 'Gym Gloves',
                'slug' => Str::slug('Gym Gloves'),
                'price' => 2700.00,
                'quantity' => 35,
                'discount_amount' => 270.00,
                'actual_amount' => 2430.00,
                'image' => 'products/gym-gloves.jpg',
                'description' => 'Durable gym gloves for weightlifting.',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // New design
            ],
            [
                'name' => 'Resistance Bands',
                'slug' => Str::slug('Resistance Bands'),
                'price' => 4050.00,
                'quantity' => 30,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/resistance-bands.jpg',
                'description' => 'Set of resistance bands for strength training.',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Unique fitness tool
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 0,
            ],

            // Category 7: Books & Stationery (category_id: 7)
            [
                'name' => 'Classic Novel Collection',
                'slug' => Str::slug('Classic Novel Collection'),
                'price' => 6750.00,
                'quantity' => 25,
                'discount_amount' => 675.00,
                'actual_amount' => 6075.00,
                'image' => 'products/classic-novel-collection.jpg',
                'description' => 'A set of timeless classic novels.',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium book set
                'is_selling' => 0,
                'is_popular' => 1,  // Popular among readers
                'is_new' => 0,
            ],
            [
                'name' => 'Notebook A5',
                'slug' => Str::slug('Notebook A5'),
                'price' => 675.00,
                'quantity' => 100,
                'discount_amount' => 67.50,
                'actual_amount' => 607.50,
                'image' => 'products/notebook-a5.jpg',
                'description' => 'A5-sized notebook with lined pages.',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales volume
                'is_popular' => 1,  // Widely used
                'is_new' => 0,
            ],
            [
                'name' => 'Pen Set',
                'slug' => Str::slug('Pen Set'),
                'price' => 1350.00,
                'quantity' => 80,
                'discount_amount' => 135.00,
                'actual_amount' => 1215.00,
                'image' => 'products/pen-set.jpg',
                'description' => 'Set of high-quality pens for writing.',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Textbook Physics',
                'slug' => Str::slug('Textbook Physics'),
                'price' => 4050.00,
                'quantity' => 20,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/textbook-physics.jpg',
                'description' => 'Comprehensive physics textbook for students.',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Essential academic item
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // New edition
            ],
            [
                'name' => 'Sticky Notes',
                'slug' => Str::slug('Sticky Notes'),
                'price' => 540.00,
                'quantity' => 90,
                'discount_amount' => 54.00,
                'actual_amount' => 486.00,
                'image' => 'products/sticky-notes.jpg',
                'description' => 'Colorful sticky notes for organization.',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High demand
                'is_popular' => 1,  // Popular stationery
                'is_new' => 0,
            ],

            // Category 8: Toys & Games (category_id: 8)
            [
                'name' => 'Building Block Set',
                'slug' => Str::slug('Building Block Set'),
                'price' => 4050.00,
                'quantity' => 60,
                'discount_amount' => 675.00,
                'actual_amount' => 3375.00,
                'image' => 'products/building-block-set.jpg',
                'description' => 'Creative building blocks for kids.',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Creative standout
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Board Game Classic',
                'slug' => Str::slug('Board Game Classic'),
                'price' => 5400.00,
                'quantity' => 30,
                'discount_amount' => 540.00,
                'actual_amount' => 4860.00,
                'image' => 'products/board-game-classic.jpg',
                'description' => 'Classic board game for family fun.',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular family game
                'is_new' => 1,     // New edition
            ],
            [
                'name' => 'Stuffed Teddy Bear',
                'slug' => Str::slug('Stuffed Teddy Bear'),
                'price' => 2700.00,
                'quantity' => 40,
                'discount_amount' => 270.00,
                'actual_amount' => 2430.00,
                'image' => 'products/stuffed-teddy-bear.jpg',
                'description' => 'Soft teddy bear for kids.',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Beloved toy
                'is_new' => 0,
            ],
            [
                'name' => 'Puzzle 500 Pieces',
                'slug' => Str::slug('Puzzle 500 Pieces'),
                'price' => 2025.00,
                'quantity' => 50,
                'discount_amount' => 202.50,
                'actual_amount' => 1822.50,
                'image' => 'products/puzzle-500-pieces.jpg',
                'description' => '500-piece puzzle for all ages.',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 1,     // New design
            ],
            [
                'name' => 'Remote Control Car',
                'slug' => Str::slug('Remote Control Car'),
                'price' => 6750.00,
                'quantity' => 20,
                'discount_amount' => 675.00,
                'actual_amount' => 6075.00,
                'image' => 'products/remote-control-car.jpg',
                'description' => 'Fast remote control car for kids.',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Exciting toy
                'is_selling' => 0,
                'is_popular' => 1,  // Trendy
                'is_new' => 0,
            ],

            // Category 9: Health & Wellness (category_id: 9)
            [
                'name' => 'Vitamin D Supplements',
                'slug' => Str::slug('Vitamin D Supplements'),
                'price' => 2700.00,
                'quantity' => 80,
                'discount_amount' => 270.00,
                'actual_amount' => 2430.00,
                'image' => 'products/vitamin-d-supplements.jpg',
                'description' => 'Essential Vitamin D for bone health.',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Essential health item
                'is_selling' => 1,  // High demand
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Protein Powder',
                'slug' => Str::slug('Protein Powder'),
                'price' => 5400.00,
                'quantity' => 30,
                'discount_amount' => 540.00,
                'actual_amount' => 4860.00,
                'image' => 'products/protein-powder.jpg',
                'description' => 'High-quality protein powder for muscle gain.',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular fitness supplement
                'is_new' => 1,     // New flavor
            ],
            [
                'name' => 'Herbal Tea',
                'slug' => Str::slug('Herbal Tea'),
                'price' => 1350.00,
                'quantity' => 60,
                'discount_amount' => 135.00,
                'actual_amount' => 1215.00,
                'image' => 'products/herbal-tea.jpg',
                'description' => 'Calming herbal tea blend.',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Trending wellness
                'is_new' => 0,
            ],
            [
                'name' => 'Omega-3 Capsules',
                'slug' => Str::slug('Omega-3 Capsules'),
                'price' => 4050.00,
                'quantity' => 40,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/omega-3-capsules.jpg',
                'description' => 'Omega-3 for heart and brain health.',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Key health supplement
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Yoga Block',
                'slug' => Str::slug('Yoga Block'),
                'price' => 2025.00,
                'quantity' => 50,
                'discount_amount' => 202.50,
                'actual_amount' => 1822.50,
                'image' => 'products/yoga-block.jpg',
                'description' => 'Supportive yoga block for stretching.',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular yoga accessory
                'is_new' => 0,
            ],

            // Category 10: Jewelry & Watches (category_id: 10)
            [
                'name' => 'Gold Necklace',
                'slug' => Str::slug('Gold Necklace'),
                'price' => 40500.00,
                'quantity' => 10,
                'discount_amount' => 6750.00,
                'actual_amount' => 33750.00,
                'image' => 'products/gold-necklace.jpg',
                'description' => 'Elegant gold necklace for special occasions.',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Luxury item
                'is_selling' => 0,
                'is_popular' => 1,  // Trendy jewelry
                'is_new' => 0,
            ],
            [
                'name' => 'Silver Bracelet',
                'slug' => Str::slug('Silver Bracelet'),
                'price' => 13500.00,
                'quantity' => 15,
                'discount_amount' => 1350.00,
                'actual_amount' => 12150.00,
                'image' => 'products/silver-bracelet.jpg',
                'description' => 'Stylish silver bracelet with intricate design.',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 1,     // New arrival
            ],
            [
                'name' => 'Analog Watch',
                'slug' => Str::slug('Analog Watch'),
                'price' => 20250.00,
                'quantity' => 20,
                'discount_amount' => 2025.00,
                'actual_amount' => 18225.00,
                'image' => 'products/analog-watch.jpg',
                'description' => 'Classic analog watch with leather strap.',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Classic standout
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Diamond Earrings',
                'slug' => Str::slug('Diamond Earrings'),
                'price' => 67500.00,
                'quantity' => 5,
                'discount_amount' => 6750.00,
                'actual_amount' => 60750.00,
                'image' => 'products/diamond-earrings.jpg',
                'description' => 'Sparkling diamond earrings for elegance.',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Luxury feature
                'is_selling' => 0,
                'is_popular' => 1,  // High-end trend
                'is_new' => 0,
            ],
            [
                'name' => 'Beaded Anklet',
                'slug' => Str::slug('Beaded Anklet'),
                'price' => 4050.00,
                'quantity' => 25,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/beaded-anklet.jpg',
                'description' => 'Colorful beaded anklet for casual wear.',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // Popular accessory
                'is_popular' => 0,
                'is_new' => 0,
            ],

            // Category 11: Automotive (category_id: 11)
            [
                'name' => 'Car Wax Kit',
                'slug' => Str::slug('Car Wax Kit'),
                'price' => 4725.00,
                'quantity' => 35,
                'discount_amount' => 675.00,
                'actual_amount' => 4050.00,
                'image' => 'products/car-wax-kit.jpg',
                'description' => 'Complete car waxing kit for a shiny finish.',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Complete kit
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Tire Inflator',
                'slug' => Str::slug('Tire Inflator'),
                'price' => 6750.00,
                'quantity' => 20,
                'discount_amount' => 675.00,
                'actual_amount' => 6075.00,
                'image' => 'products/tire-inflator.jpg',
                'description' => 'Portable tire inflator for emergencies.',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Useful and trendy
                'is_new' => 1,     // New model
            ],
            [
                'name' => 'Car Floor Mats',
                'slug' => Str::slug('Car Floor Mats'),
                'price' => 5400.00,
                'quantity' => 30,
                'discount_amount' => 540.00,
                'actual_amount' => 4860.00,
                'image' => 'products/car-floor-mats.jpg',
                'description' => 'Durable floor mats for car interiors.',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Engine Oil',
                'slug' => Str::slug('Engine Oil'),
                'price' => 4050.00,
                'quantity' => 40,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/engine-oil.jpg',
                'description' => 'High-performance engine oil for vehicles.',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // High-performance
                'is_selling' => 0,
                'is_popular' => 1,  // Essential item
                'is_new' => 0,
            ],
            [
                'name' => 'Car Air Freshener',
                'slug' => Str::slug('Car Air Freshener'),
                'price' => 1350.00,
                'quantity' => 50,
                'discount_amount' => 135.00,
                'actual_amount' => 1215.00,
                'image' => 'products/car-air-freshener.jpg',
                'description' => 'Long-lasting air freshener for cars.',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High demand
                'is_popular' => 0,
                'is_new' => 0,
            ],

            // Category 12: Pet Supplies (category_id: 12)
            [
                'name' => 'Dog Food',
                'slug' => Str::slug('Dog Food'),
                'price' => 6075.00,
                'quantity' => 45,
                'discount_amount' => 1350.00,
                'actual_amount' => 4725.00,
                'image' => 'products/dog-food.jpg',
                'description' => 'Nutritious dry dog food for all breeds.',
                'category_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Premium pet food
                'is_selling' => 1,  // Best-seller
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Cat Toy Mouse',
                'slug' => Str::slug('Cat Toy Mouse'),
                'price' => 675.00,
                'quantity' => 70,
                'discount_amount' => 67.50,
                'actual_amount' => 607.50,
                'image' => 'products/cat-toy-mouse.jpg',
                'description' => 'Interactive mouse toy for cats.',
                'category_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Popular cat toy
                'is_new' => 1,     // New design
            ],
            [
                'name' => 'Pet Bed',
                'slug' => Str::slug('Pet Bed'),
                'price' => 4050.00,
                'quantity' => 25,
                'discount_amount' => 405.00,
                'actual_amount' => 3645.00,
                'image' => 'products/pet-bed.jpg',
                'description' => 'Cozy pet bed for dogs and cats.',
                'category_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 1,  // Cozy standout
                'is_selling' => 0,
                'is_popular' => 0,
                'is_new' => 0,
            ],
            [
                'name' => 'Dog Leash',
                'slug' => Str::slug('Dog Leash'),
                'price' => 2025.00,
                'quantity' => 40,
                'discount_amount' => 202.50,
                'actual_amount' => 1822.50,
                'image' => 'products/dog-leash.jpg',
                'description' => 'Durable leash for dog walking.',
                'category_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 1,  // High sales
                'is_popular' => 1,  // Popular pet item
                'is_new' => 0,
            ],
            [
                'name' => 'Fish Food',
                'slug' => Str::slug('Fish Food'),
                'price' => 1350.00,
                'quantity' => 60,
                'discount_amount' => 135.00,
                'actual_amount' => 1215.00,
                'image' => 'products/fish-food.jpg',
                'description' => 'Nutritious flakes for aquarium fish.',
                'category_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
                'is_feature' => 0,
                'is_selling' => 0,
                'is_popular' => 1,  // Common fish item
                'is_new' => 0,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
    }
}

}